# Generated by Django 5.2.17 on 2026-09-10 17:10

import django.db.models.deletion
import django.db.models.manager
import safe.apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_it', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('name_de', models.CharField(max_length=120)),
                ('is_eu', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'country',
                'ordering': ['name_it'],
            },
        ),
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('cause', 'cause'), ('location_type', 'location_type'), ('slope_difficulty', 'slope_difficulty'), ('weather', 'weather'), ('snow_condition', 'snow_condition'), ('wind', 'wind'), ('visibility', 'visibility'), ('location_feature', 'location_feature'), ('traffic', 'traffic'), ('snow_making', 'snow_making'), ('event_type', 'event_type'), ('gender', 'gender'), ('equipment', 'equipment'), ('equipment_owner', 'equipment_owner'), ('equipment_condition', 'equipment_condition'), ('protection', 'protection'), ('insurance', 'insurance'), ('accommodation', 'accommodation'), ('destination', 'destination'), ('diagnosis', 'diagnosis'), ('injury_place', 'injury_place'), ('body_part', 'body_part'), ('evacuation_mean', 'evacuation_mean'), ('responsibility', 'responsibility'), ('person_role', 'person_role'), ('rescue_refusal', 'rescue_refusal'), ('team_body', 'team_body')], max_length=40)),
                ('code', models.SlugField(max_length=60)),
                ('label_it', models.CharField(max_length=120)),
                ('label_en', models.CharField(max_length=120)),
                ('label_de', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(blank=True, default='', max_length=9)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='lookups.lookupvalue')),
            ],
            options={
                'db_table': 'lookup_value',
                'ordering': ['dimension', 'sort_order', 'code'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLookupDisabled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('lookup_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_for', to='lookups.lookupvalue')),
            ],
            options={
                'db_table': 'company_lookup_disabled',
            },
        ),
        migrations.AddIndex(
            model_name='lookupvalue',
            index=models.Index(fields=['dimension', 'sort_order'], name='ix_lookup_dim'),
        ),
        migrations.AddConstraint(
            model_name='lookupvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('dimension', 'code'), name='ux_lookup_global_dim_code'),
        ),
        migrations.AddConstraint(
            model_name='lookupvalue',
            constraint=models.UniqueConstraint(fields=('dimension', 'code', 'company'), name='ux_lookup_company_dim_code'),
        ),
        migrations.AddConstraint(
            model_name='lookupvalue',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[a-z0-9_]+$')), name='chk_lookup_code'),
        ),
        migrations.AddConstraint(
            model_name='companylookupdisabled',
            constraint=models.UniqueConstraint(fields=('company', 'lookup_value'), name='pk_company_lookup_disabled'),
        ),
    ]
