# Generated by Django 5.2.17 on 2026-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0003_condition_first_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupvalue',
            name='dimension',
            field=models.CharField(choices=[('cause', 'cause'), ('location_type', 'location_type'), ('slope_difficulty', 'slope_difficulty'), ('weather', 'weather'), ('snow_condition', 'snow_condition'), ('wind', 'wind'), ('visibility', 'visibility'), ('location_feature', 'location_feature'), ('traffic', 'traffic'), ('snow_making', 'snow_making'), ('event_type', 'event_type'), ('gender', 'gender'), ('equipment', 'equipment'), ('equipment_owner', 'equipment_owner'), ('equipment_condition', 'equipment_condition'), ('protection', 'protection'), ('insurance', 'insurance'), ('accommodation', 'accommodation'), ('destination', 'destination'), ('diagnosis', 'diagnosis'), ('injury_place', 'injury_place'), ('body_part', 'body_part'), ('evacuation_mean', 'evacuation_mean'), ('responsibility', 'responsibility'), ('person_role', 'person_role'), ('rescue_refusal', 'rescue_refusal'), ('team_body', 'team_body'), ('condition', 'condition'), ('first_aid', 'first_aid')], max_length=40),
        ),
    ]
