# Generated by Django 5.2.17 on 2026-09-10 17:10

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('actor_device_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=60)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['company_id', '-created_at'], name='ix_audit_company_time'), models.Index(fields=['company_id', 'object_type', 'object_id'], name='ix_audit_object')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
