# Generated by Django 5.2.17 on 2026-09-10 17:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.manager
import safe.apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstatAdminUnit',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('region', 'Regione'), ('province', 'Provincia'), ('municipality', 'Comune')], max_length=12)),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('parent_code', models.CharField(blank=True, default='', max_length=12)),
                ('edition_year', models.PositiveSmallIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'istat_admin_unit',
                'constraints': [models.UniqueConstraint(fields=('level', 'code', 'edition_year'), name='ux_istat_unit')],
            },
        ),
        migrations.CreateModel(
            name='SkiArea',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('regional_code', models.CharField(blank=True, default='', max_length=40)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
            ],
            options={
                'db_table': 'ski_area',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('lift_type', models.CharField(blank=True, default='', max_length=40)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('ski_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='territory.skiarea')),
            ],
            options={
                'db_table': 'lift',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('ski_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='territory.skiarea')),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('regional_code', models.CharField(blank=True, default='', max_length=40)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('difficulty', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'slope_difficulty'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slopes', to='territory.zone')),
            ],
            options={
                'db_table': 'slope',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='skiarea',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='ux_ski_area_company_name'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['company', 'ski_area'], name='ix_zone_company_area'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('ski_area', 'name'), name='ux_zone_area_name'),
        ),
        migrations.AddIndex(
            model_name='slope',
            index=models.Index(fields=['company', 'zone'], name='ix_slope_company_zone'),
        ),
        migrations.AddConstraint(
            model_name='slope',
            constraint=models.UniqueConstraint(fields=('zone', 'name'), name='ux_slope_zone_name'),
        ),
    ]
