# Generated by Django 5.2.17 on 2026-09-10 17:10

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import safe.apps.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('jobs', '0001_initial'),
        ('lookups', '0001_initial'),
        ('org', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('territory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_format', models.CharField(max_length=20)),
                ('mapping', models.JSONField(default=dict)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_ok', models.IntegerField(default=0)),
                ('rows_error', models.IntegerField(default=0)),
                ('report', models.JSONField(default=list)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.asyncjob')),
            ],
            options={
                'db_table': 'import_batch',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('legacy_id', models.CharField(blank=True, default='', max_length=40)),
                ('dateandtime', models.DateTimeField()),
                ('location_description', models.CharField(blank=True, default='', max_length=500)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('cause_note', models.TextField(blank=True, default='')),
                ('service_report', models.BooleanField(default=False)),
                ('witnesses', models.BooleanField(blank=True, null=True)),
                ('caller', models.CharField(blank=True, default='', max_length=120)),
                ('call_received_at', models.TimeField(blank=True, null=True)),
                ('time_since_incident', models.DurationField(blank=True, null=True)),
                ('external_rescue_call_at', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('valid', models.BooleanField(default=False)),
                ('fully_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_count', models.PositiveIntegerField(default=0)),
                ('last_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('istat_comune_code', models.CharField(blank=True, default='', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cause', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'cause'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='devices.mobiledevice')),
                ('difficulty', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'slope_difficulty'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('event_type', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'event_type'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('location_feature', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'location_feature'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('location_type', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'location_type'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ski_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='territory.skiarea')),
                ('slope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='territory.slope')),
                ('snow_condition', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'snow_condition'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('snow_making', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'snow_making'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='org.team')),
                ('traffic', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'traffic'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('visibility', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'visibility'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('weather', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'weather'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('wind', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'wind'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='territory.zone')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='rescue.importbatch')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-dateandtime'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('initials_firstname', models.CharField(blank=True, default='', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{0,3}$', 'Solo iniziali maiuscole (max 3).')])),
                ('initials_surname', models.CharField(blank=True, default='', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{0,3}$', 'Solo iniziali maiuscole (max 3).')])),
                ('pii_ciphertext', models.BinaryField(blank=True, null=True)),
                ('pii_key_wrapped', models.BinaryField(blank=True, null=True)),
                ('pii_key_version', models.PositiveIntegerField(blank=True, null=True)),
                ('pii_fields', models.JSONField(blank=True, default=list)),
                ('helmet', models.BooleanField(blank=True, null=True)),
                ('equipment_note', models.TextField(blank=True, default='')),
                ('insurance_note', models.TextField(blank=True, default='')),
                ('accommodation_note', models.TextField(blank=True, default='')),
                ('destination_note', models.TextField(blank=True, default='')),
                ('diagnosis_note', models.TextField(blank=True, default='')),
                ('evacuation_means_note', models.TextField(blank=True, default='')),
                ('delivered_at', models.TimeField(blank=True, null=True)),
                ('administrative_violations', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('age_class_snapshot', models.CharField(blank=True, default='', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'accommodation'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('country', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.country')),
                ('destination', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'destination'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('diagnosis', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'diagnosis'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('equipment', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'equipment'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('equipment_condition', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'equipment_condition'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('equipment_owner', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'equipment_owner'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='rescue.event')),
                ('gender', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'gender'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('gravest_injury', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'body_part'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('injury_place', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'injury_place'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('insurance', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'insurance'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('rescue_refusal', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'rescue_refusal'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('responsibility', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'responsibility'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('role', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'person_role'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
            ],
            options={
                'db_table': 'person',
                'ordering': ['event', 'sequence'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PersonProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_protections', to='rescue.person')),
                ('protection', models.ForeignKey(limit_choices_to={'dimension': 'protection'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
            ],
            options={
                'db_table': 'person_protection',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='protections',
            field=models.ManyToManyField(related_name='+', through='rescue.PersonProtection', to='lookups.lookupvalue'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'season',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='chk_season_range')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='rescue.season'),
        ),
        migrations.CreateModel(
            name='EventOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='rescue.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_operator',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('event', 'position'), name='pk_event_operator')],
            },
        ),
        migrations.CreateModel(
            name='PersonDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(limit_choices_to={'dimension': 'diagnosis'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_diagnoses', to='rescue.person')),
            ],
            options={
                'db_table': 'person_diagnosis',
                'constraints': [models.UniqueConstraint(fields=('person', 'diagnosis'), name='pk_person_diagnosis')],
            },
        ),
        migrations.CreateModel(
            name='PersonEvacuationMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mean', models.ForeignKey(limit_choices_to={'dimension': 'evacuation_mean'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_means', to='rescue.person')),
            ],
            options={
                'db_table': 'person_evacuation_mean',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['mean'], name='ix_pem_mean')],
                'constraints': [models.UniqueConstraint(fields=('person', 'order'), name='pk_person_evacuation_order'), models.UniqueConstraint(fields=('person', 'mean'), name='ux_person_evacuation_mean')],
            },
        ),
        migrations.CreateModel(
            name='PersonInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('primary', 'Principale'), ('secondary', 'Secondaria')], max_length=10)),
                ('body_part', models.ForeignKey(limit_choices_to={'dimension': 'body_part'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='rescue.person')),
            ],
            options={
                'db_table': 'person_injury',
                'constraints': [models.UniqueConstraint(fields=('person', 'body_part'), name='pk_person_injury')],
            },
        ),
        migrations.AddConstraint(
            model_name='personprotection',
            constraint=models.UniqueConstraint(fields=('person', 'protection'), name='pk_person_protection'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'event'], name='ix_person_company_event'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'country'], name='ix_person_country'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'diagnosis'], name='ix_person_diagnosis'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'equipment'], name='ix_person_equipment'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(condition=models.Q(('pii_ciphertext__isnull', False)), fields=['company', 'anonymized_at'], name='ix_person_retention'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='ux_person_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('event', 'sequence'), name='ux_person_event_seq'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pii_ciphertext__isnull', True), ('pii_key_wrapped__isnull', True)), models.Q(('pii_ciphertext__isnull', False), ('pii_key_wrapped__isnull', False)), _connector='OR'), name='chk_person_pii_pair'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', '-dateandtime'], name='ix_event_company_date'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'season', 'zone'], name='ix_event_season_zone'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'team', 'dateandtime'], name='ix_event_team_date'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'slope'], name='ix_event_slope'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'ski_area'], name='ix_event_ski_area'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'locked_at'], name='ix_event_locked'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='ux_event_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id', ''), _negated=True), fields=('company', 'legacy_id'), name='ux_event_legacy'),
        ),
    ]
