# Generated by Django 5.2.17 on 2026-09-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0004_person_condition_first_aid'),
        ('rescue', '0002_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(limit_choices_to={'dimension': 'condition'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_conditions', to='rescue.person')),
            ],
            options={
                'db_table': 'person_condition',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='conditions',
            field=models.ManyToManyField(related_name='+', through='rescue.PersonCondition', to='lookups.lookupvalue'),
        ),
        migrations.CreateModel(
            name='PersonFirstAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_aid', models.ForeignKey(limit_choices_to={'dimension': 'first_aid'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_first_aid', to='rescue.person')),
            ],
            options={
                'db_table': 'person_first_aid',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='first_aid',
            field=models.ManyToManyField(related_name='+', through='rescue.PersonFirstAid', to='lookups.lookupvalue'),
        ),
        migrations.AddConstraint(
            model_name='personcondition',
            constraint=models.UniqueConstraint(fields=('person', 'condition'), name='pk_person_condition'),
        ),
        migrations.AddConstraint(
            model_name='personfirstaid',
            constraint=models.UniqueConstraint(fields=('person', 'first_aid'), name='pk_person_first_aid'),
        ),
    ]
