# Generated by Django 5.2.17 on 2026-09-10 17:10

import django.db.models.deletion
import django.db.models.manager
import safe.apps.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('pdf_report', 'PDF rapporto'), ('export_dataset', 'Export dataset'), ('export_regional', 'Export regionale'), ('import_historical', 'Import storico'), ('rebuild_tiles', 'Rigenerazione tile'), ('anonymize', 'Anonimizzazione'), ('reencrypt', 'Ri-cifratura')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'In coda'), ('running', 'In esecuzione'), ('done', 'Completato'), ('failed', 'Fallito'), ('cancelled', 'Annullato')], default='queued', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('result_object_key', models.CharField(blank=True, default='', max_length=300)),
                ('result_filename', models.CharField(blank=True, default='', max_length=200)),
                ('result_mime', models.CharField(blank=True, default='', max_length=100)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'async_job',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_code', models.CharField(max_length=40)),
                ('format', models.CharField(choices=[('xlsx', 'XLSX'), ('xls', 'XLS'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=4)),
                ('filters', models.JSONField(default=dict)),
                ('administrative_area_code', models.CharField(blank=True, default='', max_length=12)),
                ('quality_preview', models.JSONField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_run', to='jobs.asyncjob')),
            ],
            options={
                'db_table': 'export_run',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='asyncjob',
            index=models.Index(fields=['company', 'status', '-created_at'], name='ix_job_company_status'),
        ),
    ]
