# Generated by Django 5.2.17 on 2026-09-10 17:10

import safe.apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tenant_type', models.CharField(choices=[('company', 'Società di gestione'), ('authority', 'Ente pubblico')], default='company', max_length=16)),
                ('timezone', models.CharField(default='Europe/Rome', max_length=64)),
                ('default_locale', models.CharField(default='it', max_length=5)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('retention_identity_years', models.PositiveSmallIntegerField(default=10)),
                ('retention_audit_years', models.PositiveSmallIntegerField(default=10)),
                ('data_version', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
    ]
