# Generated by Django 5.2.17 on 2026-09-10 17:10

import django.db.models.deletion
import django.db.models.manager
import safe.apps.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oidc_subject', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('keycloak_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('locale', models.CharField(default='it', max_length=5)),
                ('status', models.CharField(choices=[('invited', 'Invitato'), ('active', 'Attivo'), ('disabled', 'Disattivato')], default='invited', max_length=10)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('mfa_required', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_user',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('body', models.ForeignKey(blank=True, limit_choices_to={'dimension': 'team_body'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.lookupvalue')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
            ],
            options={
                'db_table': 'team',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to='org.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_team',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='teams',
            field=models.ManyToManyField(related_name='users', through='org.UserTeam', to='org.team'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='ux_team_company_name'),
        ),
        migrations.AddConstraint(
            model_name='userteam',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='pk_user_team'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['company', 'status'], name='ix_user_company_status'),
        ),
    ]
