# Generated by Django 5.2.17 on 2026-09-10 17:10

import django.db.models.deletion
import django.db.models.manager
import safe.apps.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyKey',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('algorithm', models.CharField(default='x25519-sealedbox-v1', max_length=40)),
                ('public_key', models.BinaryField()),
                ('status', models.CharField(choices=[('active', 'Attiva'), ('retired', 'Ritirata')], default='active', max_length=8)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_key',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyKeyGrant',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wrapped_private_key', models.BinaryField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('company_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='crypto.companykey')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_key_grant',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyKeyRecovery',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('recovery_code', 'Codice di recupero'), ('shamir_share', 'Frazione Shamir')], max_length=16)),
                ('share_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('share_threshold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('encrypted_private_key', models.BinaryField()),
                ('kdf_params', models.JSONField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('company_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='crypto.companykey')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_key_recovery',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.UUIDField(default=safe.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm', models.CharField(default='x25519-v1', max_length=40)),
                ('public_key', models.BinaryField()),
                ('private_key_encrypted', models.BinaryField()),
                ('kdf_params', models.JSONField()),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_key',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='companykey',
            constraint=models.UniqueConstraint(fields=('company', 'version'), name='ux_company_key_version'),
        ),
        migrations.AddConstraint(
            model_name='companykey',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('company',), name='ux_company_key_active'),
        ),
        migrations.AddConstraint(
            model_name='companykeygrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('company_key', 'user'), name='ux_grant_active'),
        ),
    ]
