"""Valori iniziali dei vocabolari controllati (docs/02-schema-dati.md §3). Usati dalla migrazione di seed
e dal comando `seed_lookups`. Tuple: (code, it, en, de, sort, mapping)."""

from __future__ import annotations

A01 = "veneto_a01"

SEED: dict[str, list[tuple]] = {
    "cause": [
        (
            "accidental_fall",
            "Caduta accidentale",
            "Accidental fall",
            "Sturz",
            10,
            {A01: "Caduta accidentale"},
        ),
        (
            "collision_person",
            "Collisione con persona/e",
            "Collision with person(s)",
            "Kollision mit Person(en)",
            20,
            {A01: "Collisione altro sciatore"},
        ),
        (
            "collision_fixed_obstacle",
            "Collisione con ostacolo fisso",
            "Collision with fixed obstacle",
            "Kollision mit festem Hindernis",
            25,
            {A01: "Collisione ostacolo fisso"},
        ),
        (
            "collision_mobile_obstacle",
            "Collisione con ostacolo mobile",
            "Collision with mobile obstacle",
            "Kollision mit beweglichem Hindernis",
            30,
            {A01: "Collisione ostacolo mobile"},
        ),
        ("illness", "Malore", "Illness", "Unwohlsein", 40, {A01: "Malore"}),
        (
            "lift_fall",
            "Caduta da impianto",
            "Fall from lift",
            "Sturz vom Lift",
            45,
            {A01: "Incidente impianto risalita"},
        ),
        (
            "lift",
            "Incidente impianto di risalita",
            "Lift accident",
            "Liftunfall",
            50,
            {A01: "Incidente impianto risalita"},
        ),
        ("off_piste", "Uscita di pista", "Left the slope", "Verlassen der Piste", 60, {A01: "Altro"}),
        ("other", "Altro", "Other", "Sonstiges", 90, {A01: "Altro"}),
    ],
    "location_type": [
        ("open_slope", "Pista aperta", "Open slope", "Geöffnete Piste", 10, {}),
        (
            "off_piste",
            "Fuoripista / dominio sciabile non controllato",
            "Off-piste",
            "Abseits der Piste",
            20,
            {},
        ),
        ("closed_slope", "Pista chiusa", "Closed slope", "Gesperrte Piste", 30, {}),
        ("lift", "Impianto", "Lift", "Lift", 40, {}),
        ("race_slope", "Pista gara", "Race slope", "Rennpiste", 50, {}),
        (
            "building",
            "Edificio (es. ristorante)",
            "Building",
            "Gebäude",
            60,
            {"regional_export_exclude": True},
        ),
        ("snowpark", "Snowpark/Cross/Halfpipe", "Snowpark", "Snowpark", 70, {}),
        ("trail", "Sentieri, escursioni", "Trails, hiking", "Wanderwege", 80, {}),
        ("lift_station", "Partenza/arrivo impianto", "Lift station", "Liftstation", 85, {}),
        ("other", "Altro", "Other", "Sonstiges", 90, {}),
    ],
    "slope_difficulty": [
        ("ski_school", "Campo scuola / primi passi", "Ski school", "Übungshang", 5, {}),
        ("blue", "Azzurra", "Blue", "Blau", 10, {}),
        ("red", "Rossa", "Red", "Rot", 20, {}),
        ("black", "Nera", "Black", "Schwarz", 30, {}),
    ],
    "weather": [
        ("clear", "Sereno", "Clear", "Heiter", 10, {}),
        ("partly_cloudy", "Parzialmente nuvoloso", "Partly cloudy", "Teilweise bewölkt", 20, {}),
        ("cloudy", "Nuvoloso", "Cloudy", "Bewölkt", 30, {}),
        ("snow", "Neve", "Snow", "Schnee", 40, {}),
        ("rain", "Pioggia", "Rain", "Regen", 50, {}),
        ("fog", "Nebbia", "Fog", "Nebel", 60, {}),
        ("blizzard", "Tormenta", "Blizzard", "Schneesturm", 70, {}),
    ],
    "snow_condition": [
        ("packed", "Compatta", "Packed", "Kompakt", 10, {}),
        ("hard", "Dura", "Hard", "Hart", 20, {}),
        ("fresh", "Fresca", "Fresh", "Neuschnee", 30, {}),
        ("powder", "Farinosa", "Powder", "Pulver", 40, {}),
        ("wet", "Umida/Bagnata", "Wet", "Nass", 50, {}),
        ("crusty", "Crostosa", "Crusty", "Harsch", 60, {}),
        ("icy", "Ghiacciata", "Icy", "Vereist", 70, {}),
        ("spring", "Primaverile/marcia", "Spring snow", "Firn", 80, {}),
        ("no_snow", "Luogo privo di neve", "No snow", "Ohne Schnee", 85, {}),
    ],
    "wind": [
        ("none", "Assente", "None", "Kein Wind", 10, {}),
        ("light", "Debole", "Light", "Schwach", 20, {}),
        ("moderate", "Moderato", "Moderate", "Mäßig", 30, {}),
        ("strong", "Forte", "Strong", "Stark", 40, {}),
    ],
    "visibility": [
        ("good", "Buona", "Good", "Gut", 10, {}),
        ("fair", "Sufficiente", "Fair", "Ausreichend", 20, {}),
        ("poor", "Scarsa", "Poor", "Schlecht", 30, {}),
        ("insufficient", "Insufficiente", "Insufficient", "Unzureichend", 40, {}),
    ],
    "location_feature": [
        ("straight", "Retta", "Straight", "Gerade", 10, {}),
        ("curve", "Curva", "Curve", "Kurve", 20, {}),
        ("bump", "Dosso", "Bump", "Buckel", 30, {}),
        ("narrow", "Strettoia", "Narrow", "Engstelle", 40, {}),
        ("dip", "Avvallamento", "Dip", "Mulde", 50, {}),
        ("flat", "Pianeggiante", "Flat", "Flach", 60, {}),
        ("holes", "Con buche", "With holes", "Mit Löchern", 70, {}),
        ("jump", "Salto", "Jump", "Sprung", 80, {}),
        ("crossing", "Incrocio", "Crossing", "Kreuzung", 90, {}),
        ("steep", "Ripido", "Steep", "Steil", 100, {}),
        ("very_steep", "Molto ripido", "Very steep", "Sehr steil", 110, {}),
    ],
    "traffic": [
        ("heavy", "Intenso", "Heavy", "Stark", 10, {}),
        ("normal", "Normale", "Normal", "Normal", 20, {}),
        ("light", "Scarso", "Light", "Gering", 30, {}),
        ("other", "Altro", "Other", "Sonstiges", 90, {}),
    ],
    "snow_making": [
        ("natural", "Naturale", "Natural", "Naturschnee", 10, {}),
        ("artificial", "Artificiale", "Artificial", "Kunstschnee", 20, {}),
        ("mixed", "Misto", "Mixed", "Gemischt", 30, {}),
    ],
    "event_type": [
        ("slope_rescue", "Soccorso piste", "Slope rescue", "Pistenrettung", 10, {}),
        ("work_accident", "Infortunio sul lavoro", "Work accident", "Arbeitsunfall", 20, {}),
        ("search", "Intervento cerca persona", "Search operation", "Personensuche", 30, {}),
        ("claim_report", "Segnalazione sinistro", "Claim report", "Schadensmeldung", 40, {}),
        ("avalanche", "Intervento valanga", "Avalanche operation", "Lawineneinsatz", 50, {}),
        ("bike_park", "Bike park", "Bike park", "Bikepark", 60, {}),
        (
            "foreign_transport",
            "Trasporto da estero",
            "Transport from abroad",
            "Transport aus dem Ausland",
            70,
            {},
        ),
        (
            "at_station",
            "Presso postazioni di soccorso",
            "At rescue station",
            "An der Rettungsstation",
            80,
            {},
        ),
    ],
    "gender": [
        ("male", "Maschile", "Male", "Männlich", 10, {A01: "Maschio"}),
        ("female", "Femminile", "Female", "Weiblich", 20, {A01: "Femmina"}),
        ("other", "Altro", "Other", "Divers", 30, {}),
    ],
    "equipment": [
        ("ski", "Sci", "Ski", "Ski", 10, {A01: "Sci"}),
        ("snowboard", "Snowboard", "Snowboard", "Snowboard", 20, {A01: "Snowboard"}),
        ("ski_touring", "Sci alpinismo", "Ski touring", "Skitouren", 30, {A01: "Altro"}),
        ("telemark", "Telemark", "Telemark", "Telemark", 40, {A01: "Altro"}),
        ("xc_ski", "Sci di fondo", "Cross-country ski", "Langlauf", 50, {A01: "Altro"}),
        ("skiboard", "Skiboard", "Skiboard", "Skiboard", 55, {A01: "Altro"}),
        ("snowscoot", "Snowscoot", "Snowscoot", "Snowscoot", 56, {A01: "Altro"}),
        ("monoski", "Monoski", "Monoski", "Monoski", 57, {A01: "Altro"}),
        ("sled", "Slitta/Tubing", "Sled/Tubing", "Schlitten/Tubing", 60, {A01: "Altro"}),
        ("snowshoes", "Ciaspole", "Snowshoes", "Schneeschuhe", 65, {A01: "Altro"}),
        ("crampons", "Ramponi", "Crampons", "Steigeisen", 66, {A01: "Altro"}),
        ("hiking", "Escursionismo", "Hiking", "Wandern", 70, {A01: "Altro"}),
        ("other", "Altro", "Other", "Sonstiges", 90, {A01: "Altro"}),
    ],
    "equipment_owner": [
        ("own", "Personale", "Own", "Eigene", 10, {}),
        ("rental", "Noleggio", "Rental", "Verleih", 20, {}),
        ("borrowed", "In prestito", "Borrowed", "Geliehen", 30, {}),
        ("unknown", "Non rilevato", "Unknown", "Nicht erhoben", 90, {}),
    ],
    "equipment_condition": [
        ("poor", "Pessimo", "Poor", "Sehr schlecht", 10, {}),
        ("mediocre", "Mediocre", "Mediocre", "Mäßig", 20, {}),
        ("good", "Buono", "Good", "Gut", 30, {}),
        ("excellent", "Ottimo", "Excellent", "Ausgezeichnet", 40, {}),
        ("unknown", "Non rilevato", "Unknown", "Nicht erhoben", 90, {}),
    ],
    "protection": [
        ("back", "Paraschiena", "Back protector", "Rückenprotektor", 10, {}),
        ("neck", "Protezione del collo", "Neck protection", "Nackenschutz", 20, {}),
        ("chest", "Protezione per il torace", "Chest protection", "Brustschutz", 30, {}),
        ("gloves", "Guanti", "Gloves", "Handschuhe", 40, {}),
        ("shin", "Parastinchi", "Shin guards", "Schienbeinschoner", 50, {}),
        ("wrist", "Proteggi polso", "Wrist guards", "Handgelenkschutz", 60, {}),
        ("elbow", "Paragomiti", "Elbow pads", "Ellbogenschützer", 70, {}),
        ("knee", "Ginocchiere", "Knee pads", "Knieschützer", 80, {}),
        ("goggles", "Occhiali", "Goggles", "Brille", 90, {}),
        ("hip", "Protezione dell'anca e del bacino", "Hip protection", "Hüftschutz", 100, {}),
        ("other", "Altro", "Other", "Sonstiges", 110, {}),
        ("none", "Nessuna", "None", "Keine", 120, {}),
    ],
    "insurance": [
        ("none", "Nessuna", "None", "Keine", 10, {}),
        ("skipass", "Skipass", "Ski pass", "Skipass", 20, {}),
        ("snowcare", "Snowcare (24hassistance)", "Snowcare", "Snowcare", 30, {}),
        ("multisport", "Multisport (24hassistance)", "Multisport", "Multisport", 40, {}),
        ("interski", "Interski", "Interski", "Interski", 50, {}),
        ("carre_neige", "Carré Neige", "Carré Neige", "Carré Neige", 60, {}),
        ("caser", "Caser", "Caser", "Caser", 70, {}),
        ("other", "Altro", "Other", "Sonstiges", 90, {}),
    ],
    "accommodation": [
        (
            "tourist_facility",
            "Struttura turistica / in affitto",
            "Tourist facility / rental",
            "Unterkunft / Miete",
            10,
            {},
        ),
        ("passing_through", "Di passaggio", "Passing through", "Auf der Durchreise", 20, {}),
        (
            "own_or_friends",
            "Casa di proprietà o di amici",
            "Own or friends' home",
            "Eigenes Haus oder Freunde",
            30,
            {},
        ),
        ("other", "Altro", "Other", "Sonstiges", 90, {}),
    ],
    "destination": [
        ("trauma_center", "Centro traumatologico", "Trauma center", "Traumazentrum", 10, {}),
        ("er", "Pronto soccorso ospedaliero", "Emergency room", "Notaufnahme", 20, {}),
        ("public_clinic", "Clinica pubblica", "Public clinic", "Öffentliche Klinik", 30, {}),
        ("private_clinic", "Clinica privata", "Private clinic", "Privatklinik", 40, {}),
        ("home", "Domicilio", "Home", "Wohnort", 50, {}),
        ("deceased", "Deceduto", "Deceased", "Verstorben", 60, {}),
        ("foreign_country", "Paese estero", "Foreign country", "Ausland", 70, {}),
        ("other", "Altro", "Other", "Sonstiges", 90, {}),
    ],
    "diagnosis": [
        ("unharmed", "Illeso", "Unharmed", "Unverletzt", 5, {}),
        ("contusion", "Contusione", "Contusion", "Prellung", 10, {}),
        ("wound", "Ferita", "Wound", "Wunde", 20, {}),
        ("contused_wound", "Ferita contusa", "Contused wound", "Quetschwunde", 21, {}),
        ("penetrating_wound", "Ferita penetrante", "Penetrating wound", "Stichwunde", 22, {}),
        ("sprain", "Distorsione", "Sprain", "Verstauchung", 30, {}),
        ("fracture", "Frattura", "Fracture", "Fraktur", 40, {}),
        ("closed_fracture", "Frattura composta", "Closed fracture", "Geschlossene Fraktur", 41, {}),
        ("open_fracture", "Frattura esposta", "Open fracture", "Offene Fraktur", 42, {}),
        ("dislocation", "Lussazione", "Dislocation", "Luxation", 50, {}),
        ("muscle_injury", "Lesione muscolare", "Muscle injury", "Muskelverletzung", 60, {}),
        ("head_trauma", "Trauma cranico", "Head trauma", "Schädeltrauma", 70, {}),
        ("strain", "Stiramento", "Strain", "Zerrung", 80, {}),
        ("acl", "Legamento crociato anteriore", "ACL", "Vorderes Kreuzband", 85, {}),
        ("internal_injury", "Lesione interna", "Internal injury", "Innere Verletzung", 86, {}),
        (
            "cardiovascular",
            "Problema cardiovascolare",
            "Cardiovascular problem",
            "Herz-Kreislauf-Problem",
            87,
            {},
        ),
        ("burn", "Ustione", "Burn", "Verbrennung", 88, {}),
        ("concussion", "Commozione cerebrale (shock)", "Concussion", "Gehirnerschütterung", 89, {}),
        ("bleeding", "Emorragia", "Bleeding", "Blutung", 90, {}),
        ("intoxication", "Intossicazione", "Intoxication", "Vergiftung", 91, {}),
        ("abdominal_pain", "Dolore addominale", "Abdominal pain", "Bauchschmerzen", 92, {}),
        ("chest_pain", "Dolore toracico", "Chest pain", "Brustschmerzen", 93, {}),
        ("pulse_alteration", "Alterazione del polso", "Pulse alteration", "Pulsveränderung", 94, {}),
        ("hypothermia", "Ipotermia", "Hypothermia", "Unterkühlung", 95, {}),
        ("respiratory", "Problemi respiratori", "Respiratory problems", "Atemprobleme", 96, {}),
        ("neurological", "Neurologico", "Neurological", "Neurologisch", 97, {}),
        ("frostbite", "Congelamento", "Frostbite", "Erfrierung", 98, {}),
        ("malaise", "Malessere", "Malaise", "Unwohlsein", 99, {}),
        ("crush", "Schiacciamento", "Crush injury", "Quetschung", 100, {}),
        ("paralysis", "Paralisi", "Paralysis", "Lähmung", 101, {}),
        ("other", "Altro", "Other", "Sonstiges", 120, {}),
    ],
    "injury_place": [
        ("lower_limbs", "Arti inferiori", "Lower limbs", "Untere Gliedmaßen", 10, {}),
        ("upper_limbs", "Arti superiori", "Upper limbs", "Obere Gliedmaßen", 20, {}),
        ("head_face", "Cranio o faccia", "Head or face", "Kopf oder Gesicht", 30, {}),
        ("trunk", "Tronco", "Trunk", "Rumpf", 40, {}),
    ],
    "evacuation_mean": [
        ("akja", "Akja/Toboga", "Akja/Toboggan", "Akja", 10, {}),
        ("snowmobile", "Motoslitta", "Snowmobile", "Schneemobil", 20, {}),
        ("ambulance", "Ambulanza", "Ambulance", "Krankenwagen", 30, {}),
        ("helicopter_118", "Elicottero 118", "Helicopter 118", "Hubschrauber 118", 40, {}),
        ("lift", "Impianto", "Lift", "Lift", 50, {}),
        ("car", "Autovettura", "Car", "Auto", 60, {}),
        ("autonomous", "Autonomamente", "Autonomously", "Selbständig", 70, {}),
        ("other", "Altro", "Other", "Sonstiges", 90, {}),
    ],
    "responsibility": [
        ("shared", "Concorso di colpa", "Shared", "Mitschuld", 10, {}),
        ("own", "Propria", "Own", "Eigene", 20, {}),
        ("third_party", "Terzi", "Third party", "Dritte", 30, {}),
        ("undetectable", "Non rilevabile", "Undetectable", "Nicht feststellbar", 90, {}),
    ],
    "person_role": [
        ("involved", "Coinvolto/a", "Involved", "Beteiligt", 10, {}),
        ("witness", "Testimone", "Witness", "Zeuge", 20, {}),
        ("companion", "Accompagnatore", "Companion", "Begleiter", 30, {}),
        ("instructor", "Maestro/a di sci", "Ski instructor", "Skilehrer", 40, {}),
        ("pupil", "Allievo", "Pupil", "Schüler", 50, {}),
        ("parent", "Genitore", "Parent", "Elternteil", 60, {}),
        ("other", "Altro", "Other", "Sonstiges", 90, {}),
    ],
    "rescue_refusal": [
        ("none", "No", "No", "Nein", 10, {}),
        (
            "rescue_and_transport",
            "Soccorso e trasporto rifiutati",
            "Rescue and transport refused",
            "Rettung und Transport abgelehnt",
            20,
            {},
        ),
        (
            "transport_only",
            "Solo trasporto rifiutato",
            "Transport only refused",
            "Nur Transport abgelehnt",
            30,
            {},
        ),
        ("rescue_only", "Solo soccorso rifiutato", "Rescue only refused", "Nur Rettung abgelehnt", 40, {}),
    ],
    "condition": [
        ("conscious", "Cosciente", "Conscious", "Bei Bewusstsein", 10, {}),
        ("severe_pain", "Dolore forte", "Severe pain", "Starke Schmerzen", 20, {}),
        (
            "partially_conscious",
            "Parzialmente cosciente",
            "Partially conscious",
            "Teilweise bei Bewusstsein",
            30,
            {},
        ),
        ("unconscious", "Privo di coscienza", "Unconscious", "Bewusstlos", 40, {}),
        ("not_breathing", "Privo di respiro", "Not breathing", "Ohne Atmung", 50, {}),
        ("no_heartbeat", "Privo di battito cardiaco", "No heartbeat", "Ohne Herzschlag", 60, {}),
    ],
    "first_aid": [
        ("disinfection", "Disinfezione", "Disinfection", "Desinfektion", 10, {}),
        ("packing", "Tamponamento", "Wound packing", "Wundtamponade", 20, {}),
        ("bandage", "Fasciatura", "Bandage", "Verband", 30, {}),
        ("immobilization", "Immobilizzazione", "Immobilization", "Ruhigstellung", 40, {}),
        ("transport", "Trasporto", "Transport", "Transport", 50, {}),
    ],
    "team_body": [
        ("operator", "Gestore", "Operator", "Betreiber", 10, {}),
        ("carabinieri", "Carabinieri", "Carabinieri", "Carabinieri", 20, {}),
        ("alpine_troops", "Truppe Alpine", "Alpine Troops", "Gebirgsjäger", 30, {}),
        ("police", "Polizia", "Police", "Polizei", 40, {}),
        ("finance_guard", "Guardia di Finanza", "Finance Guard", "Finanzpolizei", 50, {}),
        ("alpine_rescue", "Soccorso Alpino", "Alpine Rescue", "Bergrettung", 60, {}),
        ("ems_118", "118", "EMS 118", "Rettungsdienst 118", 70, {}),
        ("other", "Altro", "Other", "Sonstiges", 90, {}),
    ],
}

# Parti del corpo (mappa corporea) con macro-sede padre: (code, it, en, de, sort, parent_code)
BODY_PARTS: list[tuple[str, str, str, str, int, str]] = [
    ("head", "Testa", "Head", "Kopf", 10, "head_face"),
    ("face", "Faccia", "Face", "Gesicht", 20, "head_face"),
    ("neck", "Collo", "Neck", "Hals", 30, "trunk"),
    ("chest", "Torace", "Chest", "Brustkorb", 40, "trunk"),
    ("abdomen", "Addome", "Abdomen", "Bauch", 50, "trunk"),
    ("back", "Schiena", "Back", "Rücken", 60, "trunk"),
    ("pelvis", "Bacino", "Pelvis", "Becken", 70, "trunk"),
    ("shoulder_left", "Spalla sinistra", "Left shoulder", "Linke Schulter", 100, "upper_limbs"),
    ("shoulder_right", "Spalla destra", "Right shoulder", "Rechte Schulter", 101, "upper_limbs"),
    ("arm_left", "Braccio sinistro", "Left arm", "Linker Arm", 110, "upper_limbs"),
    ("arm_right", "Braccio destro", "Right arm", "Rechter Arm", 111, "upper_limbs"),
    ("elbow_left", "Gomito sinistro", "Left elbow", "Linker Ellbogen", 120, "upper_limbs"),
    ("elbow_right", "Gomito destro", "Right elbow", "Rechter Ellbogen", 121, "upper_limbs"),
    ("forearm_left", "Avambraccio sinistro", "Left forearm", "Linker Unterarm", 130, "upper_limbs"),
    ("forearm_right", "Avambraccio destro", "Right forearm", "Rechter Unterarm", 131, "upper_limbs"),
    ("wrist_left", "Polso sinistro", "Left wrist", "Linkes Handgelenk", 140, "upper_limbs"),
    ("wrist_right", "Polso destro", "Right wrist", "Rechtes Handgelenk", 141, "upper_limbs"),
    ("hand_left", "Mano sinistra", "Left hand", "Linke Hand", 150, "upper_limbs"),
    ("hand_right", "Mano destra", "Right hand", "Rechte Hand", 151, "upper_limbs"),
    ("hip_left", "Anca sinistra", "Left hip", "Linke Hüfte", 200, "lower_limbs"),
    ("hip_right", "Anca destra", "Right hip", "Rechte Hüfte", 201, "lower_limbs"),
    ("thigh_left", "Coscia sinistra", "Left thigh", "Linker Oberschenkel", 210, "lower_limbs"),
    ("thigh_right", "Coscia destra", "Right thigh", "Rechter Oberschenkel", 211, "lower_limbs"),
    ("knee_left", "Ginocchio sinistro", "Left knee", "Linkes Knie", 220, "lower_limbs"),
    ("knee_right", "Ginocchio destro", "Right knee", "Rechtes Knie", 221, "lower_limbs"),
    ("lower_leg_left", "Gamba sinistra", "Left lower leg", "Linker Unterschenkel", 230, "lower_limbs"),
    ("lower_leg_right", "Gamba destra", "Right lower leg", "Rechter Unterschenkel", 231, "lower_limbs"),
    ("ankle_left", "Caviglia sinistra", "Left ankle", "Linker Knöchel", 240, "lower_limbs"),
    ("ankle_right", "Caviglia destra", "Right ankle", "Rechter Knöchel", 241, "lower_limbs"),
    ("foot_left", "Piede sinistro", "Left foot", "Linker Fuß", 250, "lower_limbs"),
    ("foot_right", "Piede destro", "Right foot", "Rechter Fuß", 251, "lower_limbs"),
]

# Paesi principali (ISO 3166-1 alpha-2). Elenco completo caricato dal comando `load_countries`.
COUNTRIES: list[tuple[str, str, str, str, bool]] = [
    ("IT", "Italia", "Italy", "Italien", True),
    ("DE", "Germania", "Germany", "Deutschland", True),
    ("AT", "Austria", "Austria", "Österreich", True),
    ("CH", "Svizzera", "Switzerland", "Schweiz", False),
    ("FR", "Francia", "France", "Frankreich", True),
    ("PL", "Polonia", "Poland", "Polen", True),
    ("CZ", "Cechia", "Czechia", "Tschechien", True),
    ("SK", "Slovacchia", "Slovakia", "Slowakei", True),
    ("HU", "Ungheria", "Hungary", "Ungarn", True),
    ("SI", "Slovenia", "Slovenia", "Slowenien", True),
    ("HR", "Croazia", "Croatia", "Kroatien", True),
    ("NL", "Paesi Bassi", "Netherlands", "Niederlande", True),
    ("BE", "Belgio", "Belgium", "Belgien", True),
    ("GB", "Regno Unito", "United Kingdom", "Vereinigtes Königreich", False),
    ("DK", "Danimarca", "Denmark", "Dänemark", True),
    ("SE", "Svezia", "Sweden", "Schweden", True),
    ("NO", "Norvegia", "Norway", "Norwegen", False),
    ("FI", "Finlandia", "Finland", "Finnland", True),
    ("ES", "Spagna", "Spain", "Spanien", True),
    ("PT", "Portogallo", "Portugal", "Portugal", True),
    ("RO", "Romania", "Romania", "Rumänien", True),
    ("BG", "Bulgaria", "Bulgaria", "Bulgarien", True),
    ("UA", "Ucraina", "Ukraine", "Ukraine", False),
    ("RU", "Russia", "Russia", "Russland", False),
    ("US", "Stati Uniti", "United States", "Vereinigte Staaten", False),
    ("CA", "Canada", "Canada", "Kanada", False),
    ("BR", "Brasile", "Brazil", "Brasilien", False),
    ("AU", "Australia", "Australia", "Australien", False),
    ("IL", "Israele", "Israel", "Israel", False),
    ("CN", "Cina", "China", "China", False),
    ("IE", "Irlanda", "Ireland", "Irland", True),
    ("LU", "Lussemburgo", "Luxembourg", "Luxemburg", True),
    ("LT", "Lituania", "Lithuania", "Litauen", True),
    ("LV", "Lettonia", "Latvia", "Lettland", True),
    ("EE", "Estonia", "Estonia", "Estland", True),
    ("GR", "Grecia", "Greece", "Griechenland", True),
    ("TR", "Turchia", "Türkiye", "Türkei", False),
    ("XX", "Sconosciuto", "Unknown", "Unbekannt", False),
]
